#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.pcf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-pcf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:

  pcf.yaml: |

    {{- .configuration.global | nindent 4 }}

    db_uri: mongodb://{{ $.Values.mongodb.service.name }}:{{ $.Values.mongodb.service.port }}/open5gs

    pcf:

      {{- .configuration.pcf | nindent 6 }}

{{- if eq $.Values.global.sbi.scheme "https" }}
      default:
        tls:
          server:
            scheme: https
            private_key: {{ .volume.mount }}/etc/tls/pcf.key
            cert: {{ .volume.mount }}/etc/tls/pcf.crt
            verify_client: false
            verify_client_cacert: {{ .volume.mount }}/etc/tls/ca.crt
          client:
            scheme: https
            cacert: {{ .volume.mount }}/etc/tls/ca.crt
            client_private_key: {{ .volume.mount }}/etc/tls/pcf.key
            client_cert: {{ .volume.mount }}/etc/tls/pcf.crt
{{- end }}

      sbi:
        server:
          - dev: eth0
            advertise: {{ include "open5gs-pcf.fullname" $ }}-service
            port: {{ .service.port }}
          - dev: eth0
            advertise: {{ include "open5gs-pcf.fullname" $ }}-service
            port: 443

        client:
          nrf:
            - uri: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}
          scp:
            - uri: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.scp.service.name }}:{{ $.Values.global.scp.service.port }}

      metrics:
        server:
          - address: 0.0.0.0
            port: {{ .metricService.port }}

    logger:
      {{- .configuration.logger | nindent 6 }}

{{- end }}
